# Project: mathgames
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-D_DEBUG"
WINDRESFLAGS = 
RES      = mathgames_private.res
OBJ      = main.o $(RES)
BIN      = mathgames.exe
LINKOBJ  = "main.o" "mathgames_private.res"
CLEANOBJ = "main.o" "mathgames_private.res" "mathgames.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

mathgames.exe: $(OBJ)

	$(CC) $(LINKOBJ) -o "mathgames.exe" $(LIBS)

main.o: main.c
	$(CC) -c "main.c" -o "main.o" $(CFLAGS)  -finput-charset=UTF-8 -fexec-charset=windows-1252

mathgames_private.res: mathgames_private.rc 
	$(WINDRES) -i "mathgames_private.rc" --input-format=rc -o "mathgames_private.res" -O coff $(WINDRESFLAGS) 

